#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mit4Robot_Android.Resource", IsApplication=true)]

namespace Mit4Robot_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int difficulties = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int programLanguages = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HelpMap = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HelpPascal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HelpPython = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int HelpRoad = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int HelpShop = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int HelpVariable = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int nothing = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int red = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int road = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int roadTile1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int roadTile10 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int roadTile11 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int roadTile12 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int roadTile13 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int roadTile14 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int roadTile15 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int roadTile16 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int roadTile17 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int roadTile18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int roadTile19 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int roadTile2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int roadTile20 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int roadTile21 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int roadTile22 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int roadTile23 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int roadTile24 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int roadTile25 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int roadTile26 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int roadTile27 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int roadTile3 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int roadTile4 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roadTile5 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roadTile6 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roadTile7 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int roadTile8 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int roadTile9 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int shop1 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int shop2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int shop3 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int spawn = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int SpawnFlag01 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int StoreApple = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int StoreSausage = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int terrainTile1 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int terrainTile2 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int terrainTile3 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int terrainTile4 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int terrainTile5 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int terrainTile6 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int wall = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int waterTile1 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int waterTile10 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int waterTile11 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int waterTile12 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int waterTile13 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int waterTile14 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int waterTile15 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int waterTile16 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int waterTile17 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int waterTile18 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int waterTile19 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int waterTile2 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int waterTile20 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int waterTile21 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int waterTile22 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int waterTile23 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int waterTile24 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int waterTile25 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int waterTile26 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int waterTile27 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int waterTile28 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int waterTile29 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int waterTile3 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int waterTile30 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int waterTile31 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int waterTile32 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int waterTile33 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int waterTile34 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int waterTile35 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int waterTile36 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int waterTile37 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int waterTile38 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int waterTile39 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int waterTile4 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int waterTile40 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int waterTile41 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int waterTile42 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int waterTile43 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int waterTile44 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int waterTile45 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int waterTile46 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int waterTile5 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int waterTile6 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int waterTile7 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int waterTile8 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int waterTile9 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int yellow = 2130837603;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int btnGameCodeDelete = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int btnGameCodeExecute = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int btnGameCodeOpen = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int btnGameCodeReset = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int btnGameCodeSave = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int btnGameCodeShare = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int btnGameCodeValidate = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int btnGameOptions = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int btnHelpFunctions = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int btnHelpLanguage = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int btnHelpTiles = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int btnHelpVariables = 2131165204;
			
			// aapt resource value: 0x7f070022
			public const int btnMainAchievements = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int btnMainCredits = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int btnMainHelp = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int btnMainHighscores = 2131165217;
			
			// aapt resource value: 0x7f070017
			public const int btnMainMenu = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int btnMainStart = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int btnOptions = 2131165215;
			
			// aapt resource value: 0x7f070029
			public const int btnOptionsSave = 2131165225;
			
			// aapt resource value: 0x7f07000c
			public const int imgGameMap = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070019
			public const int listHighscores = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int listLanguage = 2131165212;
			
			// aapt resource value: 0x7f070000
			public const int listViewAchievements = 2131165184;
			
			// aapt resource value: 0x7f070026
			public const int sbSpeed = 2131165222;
			
			// aapt resource value: 0x7f070002
			public const int scrollGame = 2131165186;
			
			// aapt resource value: 0x7f07001e
			public const int space1 = 2131165214;
			
			// aapt resource value: 0x7f070018
			public const int spinnerCategories = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int spinnerCategoryPlay = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int spinnerProgramLanguage = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int txtCredits = 2131165185;
			
			// aapt resource value: 0x7f070025
			public const int txtFast = 2131165221;
			
			// aapt resource value: 0x7f070011
			public const int txtGameCodeInput = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int txtGameError = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int txtGameHelp = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int txtGameOptions = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int txtGoals = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int txtHelpGeneral = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int txtOptionsSpeed = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int txtSlow = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int txtValue = 2131165224;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Achievement = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Credits = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Game = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Help = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Highscores = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LevelSelect = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Options = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ScrollableAlert = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int placeholder = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000d
			public const int btnAchievements = 2130968589;
			
			// aapt resource value: 0x7f04001d
			public const int btnAchievementsBack = 2130968605;
			
			// aapt resource value: 0x7f040002
			public const int btnBack = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int btnCancel = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int btnClose = 2130968577;
			
			// aapt resource value: 0x7f04001c
			public const int btnCreditsBack = 2130968604;
			
			// aapt resource value: 0x7f04000e
			public const int btnDifficultyEasy = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int btnDifficultyHard = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int btnDifficultyMedium = 2130968591;
			
			// aapt resource value: 0x7f04001a
			public const int btnGameCodeDelete = 2130968602;
			
			// aapt resource value: 0x7f040015
			public const int btnGameCodeOpen = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int btnGameCodeReset = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int btnGameCodeSave = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int btnGameCodeShare = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int btnGameCodeValidate = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int btnHelpFunctions = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int btnHelpLanguage = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int btnHelpTiles = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int btnHelpVariables = 2130968580;
			
			// aapt resource value: 0x7f040012
			public const int btnLanguagePascal = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int btnLanguagePython = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int btnMainCredits = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int btnMainHelp = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int btnMainHighscores = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int btnMainMenu = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int btnMainStart = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int btnOptions = 2130968588;
			
			// aapt resource value: 0x7f04001e
			public const int btnOptionsSave = 2130968606;
			
			// aapt resource value: 0x7f04001b
			public const int txtCodeField = 2130968603;
			
			// aapt resource value: 0x7f040020
			public const int txtCredits = 2130968608;
			
			// aapt resource value: 0x7f040013
			public const int txtGameHelp = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int txtGameOptions = 2130968596;
			
			// aapt resource value: 0x7f040022
			public const int txtHelpFunctions = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int txtHelpGeneral = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int txtHelpMap = 2130968612;
			
			// aapt resource value: 0x7f040028
			public const int txtHelpPascal = 2130968616;
			
			// aapt resource value: 0x7f040027
			public const int txtHelpPython = 2130968615;
			
			// aapt resource value: 0x7f040025
			public const int txtHelpRoad = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int txtHelpShop = 2130968614;
			
			// aapt resource value: 0x7f040023
			public const int txtHelpVariables = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int txtOptionsSpeed = 2130968607;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
